global using OakERP.Application.AccountsPayable.Invoices.Commands;
global using OakERP.Application.AccountsPayable.Invoices.Contracts;
global using OakERP.Application.AccountsPayable.Payments.Commands;
global using OakERP.Application.AccountsPayable.Payments.Contracts;
global using OakERP.Application.AccountsReceivable.Invoices.Commands;
global using OakERP.Application.AccountsReceivable.Invoices.Contracts;
global using OakERP.Application.AccountsReceivable.Receipts.Commands;
global using OakERP.Application.AccountsReceivable.Receipts.Contracts;
global using OakERP.Application.Posting.Contracts;
global using OakERP.Auth.Services;
global using OakERP.Common.Exceptions;
global using static OakERP.Tests.Integration.TestDates;
global using OakERP.Tests.Integration.TestSetup;
